# Generated by Django 5.2.8 on 2025-11-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
